export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const DELETE_USER = 'DELETE_USER'
export const ADD_USER = 'ADD_USER'
export const EDIT_USER = 'EDIT_USER'
export const SET_LAST_USER = 'SET_LAST_USER'
export const LOADING_DATA = 'LOADING_DATA'